import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.TEST_URL||'http://127.0.0.1:3478';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1600,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base);
 await page.locator('[data-token]').first().waitFor({timeout:45000});
 console.log('Market rows:',await page.locator('[data-token]').count());
 await page.screenshot({path:'artifacts/markets-desktop.png',fullPage:false});
 await page.locator('[data-mode="all"]').first().click();
 await page.waitForFunction(()=>document.querySelector('#result-count')?.textContent.includes('archived & active'));
 console.log('Archive:',await page.locator('#result-count').innerText());
 await page.locator('#source-filter').selectOption('sharc');
 await page.waitForFunction(()=>[...document.querySelectorAll('.market-table .source-badge')].every(e=>e.textContent==='Sharc'));
 assert.ok(await page.locator('[data-token]').count()>0);
 await page.locator('[data-star]').first().click();
 await page.locator('[data-mode="watch"]').first().click();
 await page.waitForFunction(()=>document.querySelectorAll('[data-token]').length===1);
 await page.locator('#clear-filters').click();
 await page.locator('#global-search').fill('TOLLY');
 const token='/token/0xbc43ce8dec648ea298c4275559b81d6261c90b67';
 await page.locator('#search-results a[href="'+token+'"]').click();
 await page.locator('#token-heading h1').waitFor({timeout:45000});
 await page.waitForFunction(()=>document.querySelector('#chart-empty')?.style.display==='none',{},{timeout:45000});
 assert.ok(await page.locator('#chart-container canvas').count()>0);
 assert.ok(await page.locator('#trades tr').count()>1);
 await page.screenshot({path:'artifacts/token-desktop.png',fullPage:false});
 console.log('Detail:',await page.locator('#token-heading h1').innerText(),'trades:',await page.locator('#trades tr').count());
 await page.locator('[data-tf="5m"]').click();
 await page.waitForResponse(r=>r.url().includes('/api/market/')&&r.url().includes('tf=5m'),{timeout:45000});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/token-mobile.png',fullPage:false});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Detail must not overflow viewport');
 await page.goto(base);await page.locator('[data-token]').first().waitFor();
 await page.screenshot({path:'artifacts/markets-mobile.png',fullPage:false});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'List must not overflow viewport');
 await page.route('**/api/markets?**',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":"test outage"}'}));
 const before=await page.locator('[data-token]').count();
 await page.locator('#refresh').click();
 await page.waitForFunction(()=>document.querySelector('#list-banner').textContent.includes('last received'));
 assert.equal(await page.locator('[data-token]').count(),before);
 assert.equal((await page.request.get(base+'/api/market/bad')).status(),400);
 assert.equal((await page.request.get(base+'/api/market/0xbc43ce8dec648ea298c4275559b81d6261c90b67?tf=invalid')).status(),400);
 assert.deepEqual(errors,[]);
 console.log('PASS: archive, own-source filter, watchlist, search, live chart/trades, timeframe, mobile bounds, outage retention, input validation, zero page errors.');
}finally{await browser.close();}
